// GomokuClient/src/components/Board/Board.tsx
import { useState, useEffect } from "react";
import "./Board.css";
import UserplayService from "../../service/userplay.service.ts";

interface BoardProps {
  player: string;
  nameInserted: boolean;
}

export const Board = ({ player, nameInserted }: BoardProps) => {
  const [board, setBoard] = useState(
    Array.from({ length: 19 }, () => Array(19).fill(0)),
  );
  const [size] = useState(19);
  const [goal] = useState(5);
  const [gameId, setGameId] = useState(1);
  const [myTurn, setMyTurn] = useState(false);
  const [gameStarted, setGameStarted] = useState(false);
  const [opponentName, setOpponentName] = useState("");
  const [knownOpponentName, setKnownOpponentName] = useState(false);
  const [winner, setWinner] = useState(false);
  const [winnerMessage, setWinnerMessage] = useState("");

  const getSquare = (row: number, column: number) => board[row][column];

  const isWinner = (lastPlayedRow: number, lastPlayedColumn: number) => {
    return (
      isVerticalWinner(lastPlayedRow, lastPlayedColumn) ||
      isHorizontalWinner(lastPlayedRow, lastPlayedColumn) ||
      isDiagonalWinner(lastPlayedRow, lastPlayedColumn) ||
      isOppositeDiagonalWinner(lastPlayedRow, lastPlayedColumn)
    );
  };

  useEffect(() => {
    console.log("Game started");
    UserplayService.getGameInfo().then((gameInfo) => {
      if(!gameInfo || !gameInfo.gameId || !gameInfo.yourTurn) return;
      setGameId(gameInfo.gameId);
      setMyTurn(gameInfo.yourTurn);
      setGameStarted(true);
      console.log("Game number " + gameInfo.gameId);
    })
  }, []);

  const isVerticalWinner = (
    lastPlayedRow: number,
    lastPlayedColumn: number,
  ) => {
    const square = getSquare(lastPlayedRow, lastPlayedColumn);
    let count = 1;
    let top = lastPlayedRow;
    let bottom = lastPlayedRow;

    while (count < goal) {
      top--;
      if (top < 0 || board[top][lastPlayedColumn] !== square) {
        top++;
        break;
      }
      count++;
    }

    while (count < goal) {
      bottom++;
      if (bottom >= size || board[bottom][lastPlayedColumn] !== square) {
        bottom--;
        break;
      }
      count++;
    }

    if (count === goal) {
      for (let row = top; row <= bottom; row++) {
        board[row][lastPlayedColumn] += 2;
      }
      return true;
    }
    return false;
  };

  const isHorizontalWinner = (
    lastPlayedRow: number,
    lastPlayedColumn: number,
  ) => {
    const square = getSquare(lastPlayedRow, lastPlayedColumn);
    let count = 1;
    let left = lastPlayedColumn;
    let right = lastPlayedColumn;

    while (count < goal) {
      left--;
      if (left < 0 || board[lastPlayedRow][left] !== square) {
        left++;
        break;
      }
      count++;
    }

    while (count < goal) {
      right++;
      if (right >= size || board[lastPlayedRow][right] !== square) {
        right--;
        break;
      }
      count++;
    }

    if (count === goal) {
      for (let column = left; column <= right; column++) {
        board[lastPlayedRow][column] += 2;
      }
      return true;
    }
    return false;
  };

  const isDiagonalWinner = (
    lastPlayedRow: number,
    lastPlayedColumn: number,
  ) => {
    const square = getSquare(lastPlayedRow, lastPlayedColumn);
    let count = 1;
    let top = lastPlayedRow;
    let bottom = lastPlayedRow;
    let left = lastPlayedColumn;
    let right = lastPlayedColumn;

    while (count < goal) {
      left--;
      top--;
      if (left < 0 || top < 0 || board[top][left] !== square) {
        left++;
        top++;
        break;
      }
      count++;
    }

    while (count < goal) {
      right++;
      bottom++;
      if (right >= size || bottom >= size || board[bottom][right] !== square) {
        right--;
        bottom--;
        break;
      }
      count++;
    }

    if (count === goal) {
      // let row = top;
      for (let column = left; column <= right; column++) {
        board[top++][column] += 2;
      }
      return true;
    }
    return false;
  };

  const isOppositeDiagonalWinner = (
    lastPlayedRow: number,
    lastPlayedColumn: number,
  ) => {
    const square = getSquare(lastPlayedRow, lastPlayedColumn);
    let count = 1;
    let top = lastPlayedRow;
    let bottom = lastPlayedRow;
    let left = lastPlayedColumn;
    let right = lastPlayedColumn;

    while (count < goal) {
      left--;
      bottom++;
      if (left < 0 || bottom >= size || board[bottom][left] !== square) {
        left++;
        bottom--;
        break;
      }
      count++;
    }

    while (count < goal) {
      right++;
      top--;
      if (right >= size || top < 0 || board[top][right] !== square) {
        right--;
        top++;
        break;
      }
      count++;
    }

    if (count === goal) {
      // let row = bottom;
      for (let column = left; column <= right; column++) {
        board[bottom--][column] += 2;
      }
      return true;
    }
    return false;
  };

  const userPlayed = async (row: number, column: number) => {
    if (!myTurn || !gameStarted || !nameInserted) return;
    if (board[row][column]) return;
    const newBoard = [...board];
    newBoard[row][column] = 1;
    setBoard(newBoard);
    setMyTurn(false);

    await UserplayService.userPlayed({
      gameId,
      player,
      row,
      column,
    });

    if (isWinner(row, column)) {
      setWinnerMessage("You won!");
      setWinner(true);
      setGameStarted(false);
    }
  };

  useEffect(() => {
    UserplayService.getGameInfo().then((gameInfo) => {
      if(!gameInfo || !gameInfo.gameId || !gameInfo.yourTurn) return;
      setGameId(gameInfo.gameId);
      setMyTurn(gameInfo.yourTurn);
      setGameStarted(true);
      console.log("Game number " + gameInfo.gameId);
    });

    const interval = setInterval(() => {
      if (!gameStarted) return;

      UserplayService.getLastMove(gameId).then((move) => {
        console.log(move);
        if(!move || !move.gameId || !move.row || !move.column) return;

        if (move.gameId !== gameId) return;
        if (board[move.row][move.column]) return;

        const newBoard = [...board];
        if (move.player) {
          setOpponentName(move.player);
          setKnownOpponentName(true);
        }
        newBoard[move.row][move.column] = 2;
        setBoard(newBoard);

        if (isWinner(move.row, move.column)) {
          setWinnerMessage("You lost!");
          setWinner(true);
          setGameStarted(false);
        }
        setMyTurn(true);
      });
    }, 1000);

    return () => clearInterval(interval);
  }, [gameStarted, gameId, myTurn, board]);

  return (
    <div>
      {knownOpponentName && <div>Your opponent is {opponentName}</div>}
      {winner && <div className="winner">{winnerMessage}</div>}
      <table border={1}>
        <tbody>
          {board.map((row, rowIndex) => (
            <tr key={rowIndex}>
              {row.map((_cell, columnIndex) => (
                <td
                  key={columnIndex}
                  onClick={() => userPlayed(rowIndex, columnIndex)}
                >
                  <div
                    className={`circle ${getSquare(rowIndex, columnIndex) > 0 ? "circle" : ""}
                    ${getSquare(rowIndex, columnIndex) === 1 ? "red" : ""}
                    ${getSquare(rowIndex, columnIndex) === 3 ? "dark-red" : ""}
                    ${getSquare(rowIndex, columnIndex) === 2 ? "blue" : ""}
                    ${getSquare(rowIndex, columnIndex) === 4 ? "dark-blue" : ""}`}
                  ></div>
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

// GomokuClient/src/app/board/board.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { UserplayService } from '../userplay.service';
import { Move } from '../move';
import { GameInfo } from '../game-info';
import { unescapeIdentifier } from '@angular/compiler';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrls: ['./board.component.css']
})
export class BoardComponent implements OnInit {
  @Input() player: string;
  @Input() nameInserted: boolean;

  board: number[][] = [];
  size: number = 19;
  goal: number = 5;
  gameId: number = 1;
  myTurn: boolean = false;
  gameStarted: boolean = false;
  opponentName: string = "";
  knownOpponentName: boolean = false;
  winner: boolean = false;
  winnerMessage: string = "";

  constructor(private userplayService: UserplayService) {
    for (let i:number = 0; i < this.size; i++) {
      this.board[i] = [];
      for (let j:number = 0; j < this.size; j++) {
        this.board[i][j] = 0;
      }
    }

    userplayService.getGameInfo().subscribe(gameInfo => {
      this.gameId = gameInfo.gameId;
      this.myTurn = gameInfo.yourTurn;
      this.gameStarted = true;
      console.log("Game number " + this.gameId);
    });

    setInterval(
      () => {
        if (!this.gameStarted)
          return;
        userplayService.getLastMove(this.gameId).subscribe(move => {
          console.log(move);
          console.log(move.gameId + " " + this.gameId);
          if (move.gameId != this.gameId)
            return;
          if (this.board[move.row][move.column])
            return;
          if (move.player) {
              console.log(move.player);
              this.opponentName = move.player;
              this.knownOpponentName = true;
            }
          this.board[move.row][move.column] = 2;
          if (this.isWinner(move.row, move.column)) {
            this.winnerMessage = "You lost!";
            this.winner = true;
            this.gameStarted = false;
          };
          this.myTurn = true;
        });
      }
      ,1000
    );
   }
  
  ngOnInit() {  }

  getSquare(row: number, column: number): number {
    return this.board[row][column];
  }

  userPlayed(row: number, column: number): void {
    if (!this.myTurn || !this.gameStarted || !this.nameInserted)
      return;
    if (this.board[row][column])
      return;
    this.board[row][column] = 1;
    this.myTurn = false;
    this.userplayService.userPlayed({
      gameId: this.gameId,
      player: this.player,
      row: row,
      column: column
    });
    if (this.isWinner(row, column)) {
      this.winnerMessage = "You won!";
      this.winner = true;
      this.gameStarted = false;
    }
  }

  isWinner(lastPlayedRow: number, lastPlayedColumn: number): boolean {
    return this.isVerticalWinner(lastPlayedRow, lastPlayedColumn)
      || this.isHorizontalWinner(lastPlayedRow, lastPlayedColumn)
      || this.isDiagonalWinner(lastPlayedRow, lastPlayedColumn)
      || this.isOppositeDiagonalWinner(lastPlayedRow, lastPlayedColumn);
  }

  isVerticalWinner(lastPlayedRow: number, lastPlayedColumn: number): boolean {
    let square: number = this.getSquare(lastPlayedRow, lastPlayedColumn);
    let count: number = 1;
    let top: number = lastPlayedRow;
    let bottom: number = lastPlayedRow;

    while (count < this.goal) {
      top--;
      if (top < 0 || this.board[top][lastPlayedColumn] != square) {
        top++;
        break;
      }
      count++;
    }

    while (count < this.goal) {
      bottom++;
      if (bottom >= this.size || this.board[bottom][lastPlayedColumn] != square) {
        bottom--;
        break;
      }
      count++;
    }

    if (count == this.goal) {
      for (let row: number = top; row <= bottom; row++) {
        this.board[row][lastPlayedColumn] += 2;
      }
      return true;
    } else {
      return false;
    }
  }

  isHorizontalWinner(lastPlayedRow: number, lastPlayedColumn: number): boolean {
    let square: number = this.getSquare(lastPlayedRow, lastPlayedColumn);
    let count: number = 1;
    let left: number = lastPlayedColumn;
    let right: number = lastPlayedColumn;

    while (count < this.goal) {
      left--;
      if (left < 0 || this.board[lastPlayedRow][left] != square) {
        left++;
        break;
      }
      count++;
    }

    while (count < this.goal) {
      right++;
      if (right >= this.size || this.board[lastPlayedRow][right] != square) {
        right--;
        break;
      }
      count++;
    }

    if (count == this.goal) {
      for (let column: number = left; column <= right; column++) {
        this.board[lastPlayedRow][column] += 2;
      }
      return true;
    } else {
      return false;
    }
  }

  isDiagonalWinner(lastPlayedRow: number, lastPlayedColumn: number): boolean {
    let square: number = this.getSquare(lastPlayedRow, lastPlayedColumn);
    let count: number = 1;
    let top: number = lastPlayedRow;
    let bottom: number = lastPlayedRow;
    let left: number = lastPlayedColumn;
    let right: number = lastPlayedColumn;

    while (count < this.goal) {
      left--;
      top--;
      if (left < 0 || top < 0 || this.board[top][left] != square) {
        left++;
        top++;
        break;
      }
      count++;
    }

    while (count < this.goal) {
      right++;
      bottom++;
      if (right >= this.size || bottom >= this.size || this.board[bottom][right] != square) {
        right--;
        bottom--;
        break;
      }
      count++;
    }

    if (count == this.goal) {
      let row: number = top;
      for (let column: number = left; column <= right; column++) {
        this.board[top++][column] += 2;
      }
      return true;
    } else {
      return false;
    }
  }

  isOppositeDiagonalWinner(lastPlayedRow: number, lastPlayedColumn: number): boolean {
    let square: number = this.getSquare(lastPlayedRow, lastPlayedColumn);
    let count: number = 1;
    let top: number = lastPlayedRow;
    let bottom: number = lastPlayedRow;
    let left: number = lastPlayedColumn;
    let right: number = lastPlayedColumn;

    while (count < this.goal) {
      left--;
      bottom++;
      if (left < 0 || bottom >= this.size || this.board[bottom][left] != square) {
        left++;
        bottom--;
        break;
      }
      count++;
    }

    while (count < this.goal) {
      right++;
      top--;
      if (right >= this.size || top < 0 || this.board[top][right] != square) {
        right--;
        top++;
        break;
      }
      count++;
    }

    if (count == this.goal) {
      let row: number = bottom;
      for (let column: number = left; column <= right; column++) {
        this.board[bottom--][column] += 2;
      }
      return true;
    } else {
      return false;
    }
  }
}

<div *ngIf="knownOpponentName">Your opponent is {{opponentName}}</div>
<div *ngIf="winner" class="winner">{{winnerMessage}}</div>
<table border="1">
  <tr *ngFor="let row of board; let rowIndex = index">
    <td *ngFor="let cell of row; let columnIndex = index" (click)="userPlayed(rowIndex,columnIndex);">
      <div [class.circle]="getSquare(rowIndex, columnIndex) > 0" 
        [class.red]="getSquare(rowIndex, columnIndex) == 1"
        [class.dark-red]="getSquare(rowIndex, columnIndex) == 3"
        [class.blue]="getSquare(rowIndex, columnIndex) == 2"
        [class.dark-blue]="getSquare(rowIndex, columnIndex) == 4"></div>
    </td>
  </tr>
</table>
