// GomokuClient/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  player: string;
  disabled: boolean = false;
  title: string = 'Gomoku';
  nameNotValid: boolean = false;
  nameInserted: boolean = false;
  errorMessage: string = "";

  addPlayer() : void {
    if (!this.player) {
      this.nameNotValid = true;
      this.errorMessage = "Player Name is required";
      return;
    }
    this.nameNotValid = false;
    this.nameInserted = true;
    console.log("Player is " + this.player);
    this.disabled = true;
  }
}

<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <div>
    <input [(ngModel)]="player" placeholder="Player Name" [disabled]="disabled">
    <button (click)="addPlayer();" [disabled]="disabled">Submit</button>
    <div *ngIf="nameNotValid" class="error-message">{{errorMessage}}</div>
  </div>
  <br/>
  <div class="board">
    <app-board [player]="player" [nameInserted]="nameInserted"></app-board>
  </div>
  <br/>
</div>

// GomokuClient/src/App.tsx
import { useState } from "react";
import "./App.css";
import { Board } from "./components/Board";
import { client } from "./api/client";

client.setConfig({ baseUrl: import.meta.env.VITE_API_URL });

const App = () => {
  const [player, setPlayer] = useState<string>("");
  const [disabled, setDisabled] = useState<boolean>(false);
  const [nameNotValid, setNameNotValid] = useState<boolean>(false);
  const [nameInserted, setNameInserted] = useState<boolean>(false);
  const [errorMessage, setErrorMessage] = useState<string>("");
  const title = "Gomoku";

  const addPlayer = () => {
    if (!player.trim()) {
      setNameNotValid(true);
      setErrorMessage("Player Name is required");
      return;
    }
    setNameNotValid(false);
    setNameInserted(true);
    console.log("Player is " + player);
    setDisabled(true);
  };

  return (
    <div style={{ textAlign: "center" }}>
      <h1>Welcome to {title}!</h1>
      <div>
        <input
          value={player}
          onChange={(e) => setPlayer(e.target.value)}
          placeholder="Player Name"
          disabled={disabled}
        />
        <button onClick={addPlayer} disabled={disabled}>
          Submit
        </button>
        {nameNotValid && <div className="error-message">{errorMessage}</div>}
      </div>
      <br />
      <div className="board">
        <Board player={player} nameInserted={nameInserted} />
      </div>
      <br />
    </div>
  );
};

export default App;
